### ISSUE TITLE
Some performance comparisons?

### ISSUE THREAD

**Issue by IvRRimum** [kemalyst/kemalyst#45]
Hey,

Are there any performance comparisons for kemalyst vs rails vs ...?
I think it would be very beneficial to see all that for newcomers.

Thanks!

**Comment by drujensen** [comment]
Hi @IvRRimum Thanks for the question. 

I haven't done any performance comparisons with Rails, Sinatra, Kemal, Amethyst, etc. yet. I think its too early to do comparisons since Crystal hasn't finished implementing parallelism yet.  However, I am confident it will be slower than Kemal and faster than Rails. 

Kemal is focused on speed.  It doesn't include http handlers out of the box for session, flash, csrf, cors and the router is going to be faster than Kemalyst since they are using a radix algorithm. 

Kemalyst is focused on ease of use and the MVC pattern by adding the above mentioned http handlers out of the box and the ability to chain handlers before or after the router.  Also, each handler is independent of each other and can be configured in the same way in the `/config` folder.  The [Kemalyst controller](https://github.com/drujensen/kemalyst/blob/master/src/kemalyst/controller.cr#L8) is just an [http handler](https://crystal-lang.org/api/0.22.0/HTTP/Handler.html) with helper methods for rendering or redirecting the response.  Kemalyst also provides a simple ORM, migrations, generators, sentry, icr, docker support, validations, i18n support, etc. 

Another example of difference in focus: Kemal parses the params into separate hashes for query, body, and json.  You can find the code [here](https://github.com/kemalcr/kemal/blob/master/src/kemal/param_parser.cr).  This is done for performance reasons.  Kemalyst doesn't do this and adds all of the params into one hash `params`.  There may be a small performance hit for doing it this way but the ease of development is increased by having all your params in one place.

If you are looking for the fastest lightweight framework in Crystal similar to Sinatra, I recommend using Kemal.  If your ok with "fast enough" performance but want something more like Rails, Kemalyst may be what your looking for.

**Comment by IvRRimum** [comment]
I was thinking more about comparison with Rails and Django.
Kemel is raw boned web framework, so you have to integrate your own architecture and ORM, etc.. Which i don't think a lot of people want to do.

But from my tests, Kemalyst has very good performance - Average 339.0µs for a page with 2 scaffolds.

Thanks for response.

**Comment by drujensen** [comment]
Hi @IvRRimum.  I see now that I probably read into your question further than I should have.  Do you want to help put together a comparison with other languages and comparable frameworks?

I agree that it would be useful to see the differences in performance.  Also, startup times, memory consumption and some other benefits of having a strongly typed natively compiled solution.

It might be difficult to get a good comparison since the feature sets may not be apples to apples but maybe a really small example could do the trick.

Would you be open to working on that?

**Comment by IvRRimum** [comment]
Yeah, sure. But what would be the test program? I think raw loops wouldn't cut it.

**Comment by drujensen** [comment]
What about this?  https://www.techempower.com/benchmarks/

**Comment by drujensen** [comment]
It looks like kemal / postgres didn't do so well on this test.

**Comment by IvRRimum** [comment]
Well, to be fair. Rails didn't even make it to the list :D

**Comment by IvRRimum** [comment]
Nvm, they just used different rails servers

**Comment by drujensen** [comment]
I'm thinking the threads/parallelism needs to be added before we will see significant improvements.  Currently, Crystal is on par with nodejs.

**Comment by IvRRimum** [comment]
I don't think this test really utilizes concurrency.

> In this test, the framework's ORM is used to fetch all rows from a database table containing an unknown number of Unix fortune cookie messages (the table has 12 rows, but the code cannot have foreknowledge of the table's size). An additional fortune cookie message is inserted into the list at runtime and then the list is sorted by the message text. Finally, the list is delivered to the client using a server-side HTML template. The message text must be considered untrusted and properly escaped and the UTF-8 fortune messages must be rendered properly.

**Comment by drujensen** [comment]
It looks like they hit your server with concurrent requests at different loads and then measure your responses.  

You might be able to launch multiple processes to balance the load between the core's.

"Some frameworks use process-level concurrency; have you accounted for that?" Yes, we've attempted to use production-grade configuration settings for all frameworks, including those that rely on process-level concurrency. For the EC2 tests, for example, such frameworks are configured to utilize the two virtual cores provided on an c3.large (in previous rounds, m1.large) instance. For the i7 tests, they are configured to use the eight hyper-threading cores of our hardware's i7 CPUs.

**Comment by IvRRimum** [comment]
Hmm.. Then yeah, we should wait for crystal to go concurrent.

**Comment by drujensen** [comment]
@IvRRimum I need to correct some of my terminology.   I've been saying `concurrency` when I should have been saying `parallelism` with threads.  Crystal has `concurrent` execution like node.js.

**Comment by drujensen** [comment]
@IvRRimum I've created a PR to add Kemalyst to the TechEmpower Benchmarks.  This uses the new `reuse_port` option added the HTTP::Server.  This still isn't as good as threads, but should put us on the chart.  

https://github.com/TechEmpower/FrameworkBenchmarks/pull/2784

**Comment by IvRRimum** [comment]
Nice!!

**Comment by ylluminate** [comment]
Was this seen: https://github.com/TechEmpower/FrameworkBenchmarks/pull/2784#issuecomment-303230713

**Comment by elorest** [comment]
Weird. Kemalyst model should still exist...

**Comment by ylluminate** [comment]
Curious with this being closed @drujensen, was the problem ultimately resolved?

**Comment by drujensen** [comment]
I've removed Kemalyst from the benchmarks since we added Amber. Although Amber is top Full Frameworks, we haven't solved why it's 10 times slower than expectations. We r still working on it.

**Comment by ylluminate** [comment]
Got it, thanks for clarifying. Is there an issue tracking the 10x slower issue?

**Comment by drujensen** [comment]
Thanks, good idea.  I created a ticket to track that and will provide updates as we have time to address the issue.  https://github.com/amberframework/amber/issues/273
